### ISSUE TITLE
Broken configuration and impossible to add configuration

### ISSUE THREAD

**Issue by alasta** [droso-hass/idfm#14]
Hi,

The last version has broken all my integration of IDFM.
I can't reconfig, I have the following message when I choose the station :
![idfm_error](https://user-images.githubusercontent.com/5583835/208242500-2bc6eb7b-dd65-4d7d-aa44-990c81e1e8c0.PNG)

Best regards
Alasta

**Comment by LouisForaux** [comment]
Same here

**Comment by oudoulj** [comment]
Since mid-december, something has changed on this url https://api-iv.iledefrance-mobilites.fr/lines/v2/line:IDFM:C01149/stops/stop_area:IDFM:73166/realTime
that now returns `errorMessage : "NO_REALTIME_SCHEDULES_FOUND"` 😿 

I posted about it [here as well](https://github.com/pgrimaud/horaires-ratp-api/issues/112#issuecomment-1356833208).

**Comment by drosoCode** [comment]
Can you try the new release (2.1.1) ?

@oudoulj To clarify: this integration relies directly on the official [PRIM API](https://prim.iledefrance-mobilites.fr/fr) and is not related to the *api-iv* used [here](https://me-deplacer.iledefrance-mobilites.fr/) nor to the horaires-ratp-api and idfm-card projects.

**Comment by oudoulj** [comment]
> Can you try the new release (2.1.1) ?
> 
> @oudoulj To clarify: this integration relies directly on the official [PRIM API](https://prim.iledefrance-mobilites.fr/fr) and is not related to the _api-iv_ used [here](https://me-deplacer.iledefrance-mobilites.fr/) nor to the horaires-ratp-api and idfm-card projects.

Works for me again with 2.1.1 🎉 
Thanks a lot !

**Comment by alasta** [comment]
Hi,

The last version fix the problem !
Thanks a lot !
